# Generated by Django 3.2.5 on 2023-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('no_responses', 'no Responses')], default='open', max_length=12),
        ),
    ]
