# Generated by Django 3.2.5 on 2023-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_alter_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
