# Generated by Django 3.2.5 on 2023-08-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_history', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='topics.topic')),
            ],
        ),
    ]
