FROM nginx:1.20.2

RUN rm /etc/nginx/nginx.conf
COPY nginx-confs/nginx.conf /etc/nginx/nginx.conf

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx-confs/local_nginx-prod.conf /etc/nginx/conf.d/local.conf

COPY nginx-confs/.htpasswd /etc/nginx/.htpasswd
