# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhtmlcontent',
            name='content',
            field=models.TextField(blank=True, help_text='Il y a la possibilité de rajouter du contenu HTML, il est fortement déconseillé de rajouter du css dans ce HTML. Uniquement de balises du type < p >, < b >, < br />, < u >, ... sont autorisées', null=True, verbose_name='Contenu'),
        ),
    ]
